# Generated by Django 4.2.3 on 2023-07-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_status_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(default='Work', max_length=50),
        ),
    ]
