# Generated by Django 4.2.3 on 2023-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_subtask_subtask_priority_subtask_subtask_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='name',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_priority',
            field=models.CharField(choices=[('1', 'Very Important'), ('2', 'Important'), ('3', 'Least Important')], max_length=2),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], max_length=2),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_title',
            field=models.CharField(max_length=50),
        ),
    ]
