# Generated by Django 4.2.3 on 2023-07-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_remove_subtask_name_alter_subtask_subtask_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.todo'),
        ),
    ]
