# Generated by Django 4.2.3 on 2023-07-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_alter_subtask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSubTask',
        ),
    ]
